### ISSUE TITLE
sync of ordinary files from lvm snapshot fails verify with --sparse

### ISSUE THREAD

**Issue by smemsh** [WayneD/rsync#53]
Getting some puzzling errors doing the following backup procedure on a root filesystem that's on LVM, when using sparse flag:

```
lvcreate --snapshot --name baksnap --size 3G /dev/vg0/root
mount -o ro /dev/vg0/baksnap /var/tmp/snapmnt
rsync -izaHx \
    --delete --delete-excluded --delete-after \
    --partial --inplace --sparse \
    --numeric-ids --bwlimit=640k --rsh=ssh \
    /var/tmp/snapmnt \
    bakhost:/path/to/backups/root/
```

This is causing the following errors:

```
.d..t...... etc/lvm/archive/
<f+++++++++ etc/lvm/archive/vg0_01748-450988166.vg
<f+++++++++ etc/lvm/archive/vg0_01749-1953687750.vg
.d..t...... etc/lvm/backup/
<f..t...... etc/lvm/backup/vg0
<f..t...... root/.bash_history
<f..t...... etc/lvm/backup/vg0
ERROR: etc/lvm/backup/vg0 failed verification -- update retained.
<f..t...... root/.bash_history
ERROR: root/.bash_history failed verification -- update retained.
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1287)
[sender=3.2.2pre2]
```

It repeats the above as many times as I run it.  Simply removing the `--sparse` flag makes the error go away.

This makes no sense to me in the first place, because I'm mounting the snapshot readonly, so how can it change during the copy (presumably this is why it fails verification)? And in the second place, I don't see how sparse flag would affect anything at all.  I'm using `--sparse --inplace` because I have large VM images on this filesystem, and transfers are sometimes interrupted.  However these are only very small text files showing the error (and again, they are in a readonly mount...)

I'm using Linux kernel 4.17.8 on this system, glibc 2.27, x86_64 arch.
I built 3.2.2pre2 with the following flags:
```
--disable-ipv6 --disable-openssl --disable-xxhash --disable-zstd --disable-lz4
```
```
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, no IPv6, atimes, batchfiles, inplace,
    append, ACLs, xattrs, optional protect-args, iconv, symtimes, prealloc
Checksum list:
    md5 md4 none
Compress list:
    zlibx zlib none
```

Not sure what is the issue here.  I was excited to learn about `--sparse --inplace` support, but it doesn't seem usable in what seems like an ordinary use case.  Any ideas what I could be doing wrong? Thanks.

**Comment by WayneD** [comment]
Does it fail without the compression (-z)?  Could you email me a tar file of the failing source & destination files that trigger this issue?

**Comment by WayneD** [comment]
It looks like those failing files are mentioned multiple times in the transfer. They transfer correctly once, and then the second update fails due to the file having changed compared to its checksum data (I assume). Is something returning the same file names multiple times on that mount? Try using `--debug=flist5` and seeing where things go weird.

**Comment by WayneD** [comment]
Is the remote rsync 3.1.3? There was a sparse bug in older versions that was fixed in 3.2.x.

**Comment by smemsh** [comment]
it does still fail without the compression flag.  the remote has the same version (3.2.2pre2) compiled with the same flags.  I removed the older vendor version on the system to make sure it was not being used.

another data point: I removed `--sparse` and let it run it once; no issues.  now after adding back `--sparse`, the .bash_history file is no longer in the error file list, but the lvm backup file continues to have the same error:

```
 $ sudo rsync -i -aHx --delete --delete-excluded --delete-after --sparse --partial --inplace \
   --numeric-ids --bwlimit=640k --rsh=ssh \
   /var/tmp/snapmnt/ bakhost:/path/to/backups/root/

.d..t...... etc/lvm/archive/
<f+++++++++ etc/lvm/archive/vg0_01758-373412451.vg
<f+++++++++ etc/lvm/archive/vg0_01759-2004060016.vg
.d..t...... etc/lvm/backup/
<f..t...... etc/lvm/backup/vg0
<f..t...... etc/lvm/backup/vg0
ERROR: etc/lvm/backup/vg0 failed verification -- update retained.
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1287)[sender=3.2.2pre2]
```

however I started a root shell and typed a command (which would change the .bash_history) and repeated the `lvcreate --snapshot` / `mount -o ro` / `rsync --sparse --inplace` and now the root .bash_history file is again in the error list.

it must have something to do with residing on a snapshot volume, and it being copy-on-write, and trying to seek past things, but I don't know.  It's a thick volume so I wouldn't think there would be issues with holes or underlying content being different.  it *is* on ssd, with discards, and lvm.conf passes the discards, if that makes any difference.

fwiw, it looks like `dd conv=sparse` looks for holes first by comparing fstat(2)'s st_size member with st_blocks * blocksize to see if it has fewer blocks than needed for the apparent data, but that may only be an optimization.  it might be worth considering, but there's probably some underlying issue here also.

I will also try this on a newer system because this kernel is a little old (4.17).  I will update the ticket once I'm able to try some other systems using the same scenario.

**Comment by smemsh** [comment]
another thing to mention, the remote is kernel 4.4.192 on aarch64, it appears to run in little endian mode also though like the sender (x86_64).  don't think this matters, but just in case.  I can use different hosts with more recent kernels on the sender but I will have trouble updating the remote.  I will try to reproduce with an entirely different set of hosts on both sides, but it will take me a bit.

**Comment by WayneD** [comment]
Does the receiving side have multiple rsync versions? If so, try using --rsync-path=/full/path/to/new/rsync to make sure it's running the newest rsync. The default path may not make it run the newer version. Since the errors are on non-sparse files, it makes it seem like the old 3.1.3 bug where a sparse variable wasn't getting cleared for the next non-sparse file.

**Comment by smemsh** [comment]
I had removed the system version completely to ensure it.  there's only my compiled version of rsync on the system, no other versions.

**Comment by smemsh** [comment]
ok so I ran the same test with same receiver, but using a much more recent sender system: kernel 5.3.15, glibc 2.30, also with no compression and also ensuring no other rsync was present on the system than my compiled version (3.2.2pre2 again, same build config).

basically every single file that has contents changed since my last sync, gets the error.  I had done an OS update and it sure looks like every file that it would have touched got the "failed verification -- update retained" error.  So this is pretty easy to reproduce: just modify any files since the last sync, and run the sequence.

I still have to rule out the receiver being ARM, and being an older kernel.  I might be unable to update the system to anything more recent but I can try to find another ARM board that has a newer BSP.  In the meantime I will also try a remote x86_64 system.  this will take me some more time, I will report back.

**Comment by WayneD** [comment]
Use the `--debug=nstr2` option and let me know what it outputs. Are the ordinary files actually transferred correctly (indicating some kind of checksum problem) or do they end up corrupted?  Does changing the checksum (e.g. `--cc=md4`) have any affect?

**Comment by smemsh** [comment]
> Use the `--debug=nstr2` option and let me know what it outputs

seems to only output these additional lines:
```
Client checksum list (on client): md5 md4
Server checksum list (on client): md5 md4 none
Client negotiated checksum: md5
```
I tried also the md4 option you mentioned, but no difference (note that I'm not using compression anymore in the flags for any of my tests, to rule that out).

> do they end up corrupted?

indeed the md5sums of the files on both sides do not match.  taking a look at some of them, they are indeed corrupted.  for example my /root/.bash_history has large sections of nulls written into it and the last line is truncated with no newline.  my `/bin/cat` has no ELF header at all, it contains all zeros until offset 0x2000 and then it begins matching the source file until 0x20d0 and then a bunch of zeros again.  the only other portion of the file with non-zero bytes starts at 0x7000 and then again matches the source file but this time only until 0x701c.  the rest of the file is zeros.

So, definite corruption, but I'm not convinced it's rsync until I can reproduce it with a more up to date receiver.  it could very well be a bug in the older kernel, libc or could be platform-specific since the receiver is ARM (but I doubt it, because both sides are little-endian).  I will update the ticket once I'm able to perform that test, it will take me a bit.

**Comment by smemsh** [comment]
One other thing to note, which I actually forgot, but it could be relevant: the receiver is also on LVM, but it's a thin volume (and it's ssd with discards).

There may be some assumption being violated when treating these files as sparse and seeking, which maybe would work fine if there were actual holes.  These particular files are not sparse at all, so I think perhaps there should be some detection of sparseness before trying to use a sparse algorithm, such as the `dd` heuristic mentioned earlier in this thread... it looks like `cp --sparse` does the same thing as `dd`:

```c
  if (S_ISREG (sb.st_mode))
    {
      /* Find out whether the file contains any sparse blocks. */

      if (fstat (source_desc, &sb))
        {
          error (0, errno, "%s", src_path);
          return_val = -1;
          goto ret;
        }
      
      /* If the file has fewer blocks than would normally
         be needed for a file of its size, then
         at least one of the blocks in the file is a hole. */
      if (S_ISREG (sb.st_mode) && sb.st_size > sb.st_blocks * DEV_BSIZE)
        make_holes = 1;
    }
```

**Comment by smemsh** [comment]
Come to think of it, I should be able to make a separate thin pool right on my sender system and try just a local sync to it, no need to go to a different remote host.  I will try this and report back.

**Comment by smemsh** [comment]
Ok so it reproduces locally (kernel 5.3.0, glibc 2.31, x86_64, rsync 3.2.2pre2, no other rsyncs installed) but only when using the network (`rsync ... -e ssh src/ root@localhost:/dst/`)

When the target is just a local directory, it seems to work fine with `--sparse --inplace`, even when destination is a thin pool volume.  I tried it several times, but the deltas weren't huge, a few tens of files.  Each time I was upgrading a handful of packages on my root filesystem to force the files to change, and syncing to a new ext4 LV I created again each time (I tried thick, thin with lvchange -Zn, and thin with lvchange -Zy).  It worked every time, no errors.

However when the target is over the network (localhost by ssh) I get the same errors, even when the destination is an ordinary thick LV (it failed on thin destination too, but since it reproduces on thick, I think thin is ruled out as being responsible for the bug).

However it doesn't seem to be all changed files that exhibit `failed verification -- update retained` when it's localhost network receiver, it's only some smaller subset of the changed files.  The particular changed set I reproduced it on was quite a few files because they were large packages.  I don't know if it's sensitive to the size of the change set and would have reproduced locally even without it being over ssh, if the changeset was just large enough, but it didn't in any of my tests to local filesystem (without network) and I think a few of the test runs were just as large a delta as the one that failed.

It seems easy to reproduce, just two LVs, syncing to localhost over ssh with `--sparse --inplace` (maybe the other options are relevant too, I kept them as in the original post, but no compression).  My source had 28,000 files using 2.5G, I synced it fresh without `--sparse` to a different LV after mkfs, then changed a few hundred of them (maybe 100-200mb worth), then re-ran the sync with `--sparse` and wham: `failed verification -- update retained` (but on just a few this time instead of nearly every one).

Eager for someone else to reproduce the bug at this point... seems like a real bug now: ARM is ruled out, older kernel/libc ruled out, thin volume ruled out.  Could still be LVM itself I suppose.  I can try without that but it will take me some more time.

**Comment by sheepa** [comment]
I've got the same error. Trying to transfer qcow2 images with --sparse --inplace. Initial transfer works fine, transfers after that only works if image file haven't been modified. If modified I get `WARNING: disk.qcow2 failed verification -- update retained (will try again).`

Using rsync version v3.2.3-39-g07488001 on both hosts and --rsync-path to make sure I'm running the correct version since it's not the system installed version.

**Comment by rblank** [comment]
I can confirm permanent file corruption when using `--inplace` and `--sparse` together. The symptom is errors like:

```
ERROR: path/to/file failed verification -- update retained.
```

The destination file differs from the source file, and the diff remains, despite running `rsync` multiple times. If I remove either `--inplace` or `--sparse`, there are no errors and the destination file content matches the source file. The full command that generates errors is:

```
$ rsync --stats --no-human-readable -e 'ssh -C' -acHAXS --inplace --delete --delete-excluded --exclude (...) user@src_host:/src/path /dest/path
```

ISTR remember that some time ago, using `--inplace` and `--sparse` together was forbidden. Since data corruption is a fairly serious issue, maybe this should be re-instated until the issue can be fixed?

I'm copying files between ext4 and ZFS filesystems on Linux.

```
$ rsync --version
rsync  version 3.2.3  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, hardlink-specials, symlinks, IPv6, atimes,
    batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv,
    symtimes, prealloc, stop-at, no crtimes
Optimizations:
    SIMD, asm, openssl-crypto
Checksum list:
    md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

$ uname -a
Linux xxx 5.10.52-gentoo #1 SMP PREEMPT Sat Jul 24 22:44:30 CEST 2021 x86_64 Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz GenuineIntel GNU/Linux
```

**Comment by WayneD** [comment]
I'd suggest testing the latest git version.  As a quick check, try your failing copy with the options `--no-W -M--no-W` and see if that make it stop failing.  If so, it's fixed in the latest git.

**Comment by sheepa** [comment]
> I'd suggest testing the latest git version. As a quick check, try your failing copy with the options `--no-W -M--no-W` and see if that make it stop failing. If so, it's fixed in the latest git.

I tried out the latest version (v3.2.3-90-gd881814a) and initial tests seems to be working fine. I'm not using options `--no-W -M--no-W`, just the same command that failed before. Is this expected to work? What commit fixed this?

**Comment by WayneD** [comment]
It was fixed in dbb1c2d10c127b9a5f99e3e4ee5981f5222fc7e7

**Comment by sheepa** [comment]
> It was fixed in [dbb1c2d](https://github.com/WayneD/rsync/commit/dbb1c2d10c127b9a5f99e3e4ee5981f5222fc7e7)

So just to confirm, setting `-no-W -M--no-W` doesn't matter?

**Comment by WayneD** [comment]
I've just committed another change that will cause rsync to send `--no-W` to the remote side when dealing with `--inplace --sparse`, which should make it where someone with a new rsync won't need to think about it, even when the remote rsync is an earlier version with the bug.

**Comment by smemsh** [comment]
Confirmed that I cannot reproduce my issue so far with current rsync master.  Also confirmed that `--no-W -M--no-W` seems to work with an earlier rsync where I can reproduce it.  So, this must indeed be the same as #114, and not related to LVM at all.  I will go back to using `--sparse --inplace` and if bug reappears, open new issue, thanks.
